import type { EnterpriseTableColumn } from "../../../components/data-display/EnterpriseDataTable";
import {
  asInventoryDate,
  createInventoryEditFields,
  createInventoryFormFields,
} from "../shared/inventoryDefinitionFields";
import {
  createInventoryRows,
  createInventoryViewFields,
} from "../shared/inventoryUtils";
import type { InventoryDefinition } from "../shared/types";
import type { InventoryRecord } from "../shared/types";

export type RawVeneerRecord = InventoryRecord & {
  amount: string;
  approvalStatus: string;
  bundleNumber: string;
  currency: string;
  exchangeRate: string;
  inwardDate: Date;
  inwardSrNo: string;
  inwardType: string;
  invoiceNo: string;
  itemName: string;
  length: string;
  noOfLeavesSheets: string;
  noOfTotalHours: string;
  noOfWorkingHours: string;
  palletNo: string;
  remark: string;
  shift: string;
  srNo: string;
  subCategory: string;
  supplierCode: string;
  supplierItemName: string;
  supplierName: string;
  thickness: string;
  timberColor: string;
  totalSqm: string;
  veneerSrNo: string;
  width: string;
  workers: string;
};

const rawVeneerColumns: ReadonlyArray<EnterpriseTableColumn<RawVeneerRecord>> = [
  { key: "srNo", label: "Sr No" },
  { key: "inwardSrNo", label: "Inward Sr No" },
  { key: "inwardType", label: "Inward Type" },
  { key: "inwardDate", label: "Inward Date" },
  { key: "invoiceNo", label: "Invoice No" },
  { key: "veneerSrNo", label: "Veneer Sr No" },
  { key: "supplierName", label: "Supplier Name" },
  { key: "supplierItemName", label: "Supplier Item Name" },
  { key: "supplierCode", label: "Supplier Code" },
  { key: "subCategory", label: "Sub Category" },
  { key: "itemName", label: "Item Name" },
  { key: "timberColor", label: "Timber Color" },
  { key: "bundleNumber", label: "Bundle Number" },
  { key: "palletNo", label: "Pallet No" },
  { key: "length", label: "Length" },
  { key: "width", label: "Width" },
  { key: "thickness", label: "Thickness" },
  { key: "noOfLeavesSheets", label: "No of Leaves/Sheets" },
  { key: "totalSqm", label: "Total SQM" },
  { key: "currency", label: "Currency" },
  { key: "amount", label: "Amount" },
  { key: "remark", label: "Remark" },
  { key: "approvalStatus", label: "Approval Status" },
];

const rawVeneerViewColumns = rawVeneerColumns.filter(
  (column) => column.key !== "inwardType" && column.key !== "supplierCode",
);

const rawVeneerRows = createInventoryRows<RawVeneerRecord>("raw-veneer", [
  {
    inwardSrNo: "INW-RV-2026-0001",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-02"),
    invoiceNo: "INV-PL-2401",
    veneerSrNo: "VNR-00041",
    supplierName: "Arihant Veneers LLP",
    supplierItemName: "Oak Quarter Cut Import Sheet",
    supplierCode: "SUP-ARH-014",
    subCategory: "Quarter Cut",
    itemName: "Oak Veneer",
    timberColor: "Natural Oak",
    bundleNumber: "BDL-OAK-2104",
    palletNo: "PAL-01-A",
    length: "2600 mm",
    width: "1220 mm",
    thickness: "0.60 mm",
    noOfLeavesSheets: "48",
    totalSqm: "152.340",
    currency: "INR",
    amount: "184,500.00",
    remark: "Moisture within approved inward range.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0002",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-03"),
    invoiceNo: "INV-IT-7712",
    veneerSrNo: "VNR-00042",
    supplierName: "Euro Timber Exports",
    supplierItemName: "Walnut Crown Cut Export Pack",
    supplierCode: "SUP-EUR-009",
    subCategory: "Crown Cut",
    itemName: "Walnut Veneer",
    timberColor: "Dark Walnut",
    bundleNumber: "BDL-WAL-1820",
    palletNo: "PAL-02-B",
    length: "2500 mm",
    width: "1270 mm",
    thickness: "0.55 mm",
    noOfLeavesSheets: "52",
    totalSqm: "165.100",
    currency: "USD",
    amount: "3,820.00",
    remark: "Imported bundle tagged for premium grade allocation.",
    approvalStatus: "Pending Review",
    exchangeRate: "84.25",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0003",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-05"),
    invoiceNo: "INV-DM-1189",
    veneerSrNo: "VNR-00043",
    supplierName: "Shree Wood Panels",
    supplierItemName: "Teak Natural Decorative Sheet",
    supplierCode: "SUP-SWP-022",
    subCategory: "Natural",
    itemName: "Teak Veneer",
    timberColor: "Golden Brown",
    bundleNumber: "BDL-TEK-1942",
    palletNo: "PAL-03-C",
    length: "2400 mm",
    width: "1200 mm",
    thickness: "0.50 mm",
    noOfLeavesSheets: "44",
    totalSqm: "126.720",
    currency: "INR",
    amount: "132,400.00",
    remark: "Dispatch-ready after warehouse inspection.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0004",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-07"),
    invoiceNo: "INV-PL-2407",
    veneerSrNo: "VNR-00044",
    supplierName: "Prime Timber Sources",
    supplierItemName: "Ash Crown Cut Bundle",
    supplierCode: "SUP-PTS-031",
    subCategory: "Crown Cut",
    itemName: "Ash Veneer",
    timberColor: "Light Ash",
    bundleNumber: "BDL-ASH-1106",
    palletNo: "PAL-04-A",
    length: "2550 mm",
    width: "1240 mm",
    thickness: "0.58 mm",
    noOfLeavesSheets: "50",
    totalSqm: "158.100",
    currency: "INR",
    amount: "141,800.00",
    remark: "One pallet kept aside for remeasurement.",
    approvalStatus: "On Hold",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0005",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-09"),
    invoiceNo: "INV-IT-7720",
    veneerSrNo: "VNR-00045",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Rift Cut Architectural Sheet",
    supplierCode: "SUP-NVH-011",
    subCategory: "Rift Cut",
    itemName: "Oak Veneer",
    timberColor: "Smoked Natural",
    bundleNumber: "BDL-OAK-2198",
    palletNo: "PAL-05-D",
    length: "2800 mm",
    width: "1250 mm",
    thickness: "0.65 mm",
    noOfLeavesSheets: "40",
    totalSqm: "140.000",
    currency: "EUR",
    amount: "4,650.00",
    remark: "Long-sheet inward suited for export furniture program.",
    approvalStatus: "Approved",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0006",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-11"),
    invoiceNo: "INV-DM-1198",
    veneerSrNo: "VNR-00046",
    supplierName: "Mewar Decorative Woods",
    supplierItemName: "Walnut Quarter Cut Standard Pack",
    supplierCode: "SUP-MDW-019",
    subCategory: "Quarter Cut",
    itemName: "Walnut Veneer",
    timberColor: "Rich Walnut",
    bundleNumber: "BDL-WAL-1904",
    palletNo: "PAL-06-B",
    length: "2500 mm",
    width: "1220 mm",
    thickness: "0.62 mm",
    noOfLeavesSheets: "46",
    totalSqm: "140.300",
    currency: "INR",
    amount: "168,900.00",
    remark: "Supplier label matched inward purchase order.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-RV-2026-0007",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-13"),
    invoiceNo: "INV-PL-2415",
    veneerSrNo: "VNR-00047",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Teak Crown Cut Interior Pack",
    supplierCode: "SUP-HPW-027",
    subCategory: "Crown Cut",
    itemName: "Teak Veneer",
    timberColor: "Honey Teak",
    bundleNumber: "BDL-TEK-1995",
    palletNo: "PAL-07-C",
    length: "2450 mm",
    width: "1210 mm",
    thickness: "0.52 mm",
    noOfLeavesSheets: "54",
    totalSqm: "160.080",
    currency: "INR",
    amount: "149,750.00",
    remark: "Approved with note for crown cut grain variation.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "General",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0008",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-16"),
    invoiceNo: "INV-DM-1210",
    veneerSrNo: "VNR-00048",
    supplierName: "City Timber Traders",
    supplierItemName: "Ash Natural Light Bundle",
    supplierCode: "SUP-CTT-018",
    subCategory: "Natural",
    itemName: "Ash Veneer",
    timberColor: "Soft Grey",
    bundleNumber: "BDL-ASH-1164",
    palletNo: "PAL-08-A",
    length: "2350 mm",
    width: "1180 mm",
    thickness: "0.48 mm",
    noOfLeavesSheets: "56",
    totalSqm: "155.290",
    currency: "INR",
    amount: "126,300.00",
    remark: "Pending approval after moisture retest.",
    approvalStatus: "Pending Review",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "15",
    noOfWorkingHours: "7.0",
    noOfTotalHours: "8.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0009",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-18"),
    invoiceNo: "INV-IT-7744",
    veneerSrNo: "VNR-00049",
    supplierName: "Baltic Timber Supply",
    supplierItemName: "Oak Crown Cut Premium Set",
    supplierCode: "SUP-BTS-007",
    subCategory: "Crown Cut",
    itemName: "Oak Veneer",
    timberColor: "Warm Natural",
    bundleNumber: "BDL-OAK-2237",
    palletNo: "PAL-09-D",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "0.64 mm",
    noOfLeavesSheets: "42",
    totalSqm: "141.750",
    currency: "USD",
    amount: "3,960.00",
    remark: "QC requested closer veneer serial verification.",
    approvalStatus: "Pending Review",
    exchangeRate: "84.40",
    shift: "General",
    workers: "23",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-RV-2026-0010",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-20"),
    invoiceNo: "INV-PL-2421",
    veneerSrNo: "VNR-00050",
    supplierName: "Royal Laminates India",
    supplierItemName: "Walnut Natural Feature Bundle",
    supplierCode: "SUP-RLI-029",
    subCategory: "Natural",
    itemName: "Walnut Veneer",
    timberColor: "Classic Walnut",
    bundleNumber: "BDL-WAL-1968",
    palletNo: "PAL-10-B",
    length: "2480 mm",
    width: "1230 mm",
    thickness: "0.60 mm",
    noOfLeavesSheets: "49",
    totalSqm: "149.450",
    currency: "INR",
    amount: "171,200.00",
    remark: "Released for production issue to premium line.",
    approvalStatus: "Approved",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

export const rawVeneerDefinition: InventoryDefinition<RawVeneerRecord> = {
  slug: "raw-veneer",
  title: "Raw Veneer",
  listColumns: rawVeneerColumns,
  editFields: createInventoryEditFields(rawVeneerColumns, rawVeneerRows),
  formFields: createInventoryFormFields(rawVeneerRows),
  viewFields: createInventoryViewFields(rawVeneerViewColumns),
  rows: [],
  initialSort: { key: "inwardDate", direction: "desc" },
};

