import type { EnterpriseTableColumn } from "../../../components/data-display/EnterpriseDataTable";
import {
  asInventoryDate,
  createInventoryEditFields,
  createInventoryFormFields,
} from "../shared/inventoryDefinitionFields";
import {
  createInventoryRows,
  createInventoryViewFields,
} from "../shared/inventoryUtils";
import type { InventoryDefinition } from "../shared/types";
import {
  stockColumns,
  type StockRecord,
} from "../shared/stockInventoryColumns";


const plywoodRows = createInventoryRows<StockRecord>("plywood", [
  {
    inwardSrNo: "INW-PL-2026-0001",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-03"),
    invoiceNo: "PLY-2401",
    itemSrNo: "ITM-PLY-001",
    supplierName: "Panel Craft India",
    supplierItemName: "BWP Decorative Plywood Pack",
    itemName: "BWP Plywood",
    subCategory: "Premium",
    color: "Warm Birch",
    plywoodType: "BWP",
    palletNo: "PLY-PAL-01",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "180",
    availableNoOfSheets: "154",
    totalSqm: "535.680",
    availableSqm: "458.970",
    currency: "INR",
    amount: "428,600.00",
    remark: "Primary inward for modular panel jobs.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0002",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-05"),
    invoiceNo: "PLY-2405",
    itemSrNo: "ITM-PLY-002",
    supplierName: "Western Ply Boards",
    supplierItemName: "Commercial Plywood Standard Pack",
    itemName: "Commercial Plywood",
    subCategory: "Standard",
    color: "Natural Beige",
    plywoodType: "Commercial",
    palletNo: "PLY-PAL-02",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "12 mm",
    totalNoOfSheets: "220",
    availableNoOfSheets: "194",
    totalSqm: "654.940",
    availableSqm: "577.600",
    currency: "INR",
    amount: "352,400.00",
    remark: "Issued partially to packing mockup jobs.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0003",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-07"),
    invoiceNo: "PLY-2407",
    itemSrNo: "ITM-PLY-003",
    supplierName: "Timbercore Panels",
    supplierItemName: "Marine Grade Panel Bundle",
    itemName: "Marine Plywood",
    subCategory: "Premium",
    color: "Rich Brown",
    plywoodType: "Marine",
    palletNo: "PLY-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "140",
    availableNoOfSheets: "132",
    totalSqm: "416.640",
    availableSqm: "392.840",
    currency: "INR",
    amount: "389,800.00",
    remark: "Reserved for wet-area projects.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0004",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-09"),
    invoiceNo: "PLY-7719",
    itemSrNo: "ITM-PLY-004",
    supplierName: "Scandic Wood Surfaces",
    supplierItemName: "Architectural Birch Panel Set",
    itemName: "Birch Plywood",
    subCategory: "Architectural",
    color: "Pale Birch",
    plywoodType: "Architectural",
    palletNo: "PLY-PAL-04",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "116",
    availableNoOfSheets: "95",
    totalSqm: "362.500",
    availableSqm: "296.870",
    currency: "EUR",
    amount: "6,780.00",
    remark: "Imported lot for export fixtures.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0005",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-11"),
    invoiceNo: "PLY-2411",
    itemSrNo: "ITM-PLY-005",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Flexible MDF-Backed Plywood",
    itemName: "Flexible Plywood",
    subCategory: "Specialty",
    color: "Soft Walnut",
    plywoodType: "Flexible",
    palletNo: "PLY-PAL-05",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "6 mm",
    totalNoOfSheets: "260",
    availableNoOfSheets: "218",
    totalSqm: "773.920",
    availableSqm: "648.290",
    currency: "INR",
    amount: "314,900.00",
    remark: "Used for curved cladding mockups.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0006",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-13"),
    invoiceNo: "PLY-2413",
    itemSrNo: "ITM-PLY-006",
    supplierName: "Royal Laminates India",
    supplierItemName: "Calibrated Ply Sheet Pack",
    itemName: "Calibrated Plywood",
    subCategory: "Precision",
    color: "Warm Sand",
    plywoodType: "Calibrated",
    palletNo: "PLY-PAL-06",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "168",
    availableNoOfSheets: "152",
    totalSqm: "500.650",
    availableSqm: "453.010",
    currency: "INR",
    amount: "366,200.00",
    remark: "Factory-preferred inward for CNC jobs.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0007",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-15"),
    invoiceNo: "PLY-7726",
    itemSrNo: "ITM-PLY-007",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Faced Panel Bundle",
    itemName: "Oak Faced Plywood",
    subCategory: "Architectural",
    color: "Natural Oak",
    plywoodType: "Faced",
    palletNo: "PLY-PAL-07",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "124",
    availableNoOfSheets: "110",
    totalSqm: "387.500",
    availableSqm: "343.750",
    currency: "USD",
    amount: "6,120.00",
    remark: "Held for architect-specified facade work.",
    exchangeRate: "84.50",
    shift: "Morning",
    workers: "21",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0008",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-17"),
    invoiceNo: "PLY-2417",
    itemSrNo: "ITM-PLY-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Economy Ply Stock Lot",
    itemName: "Economy Plywood",
    subCategory: "Standard",
    color: "Neutral Brown",
    plywoodType: "Commercial",
    palletNo: "PLY-PAL-08",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "9 mm",
    totalNoOfSheets: "240",
    availableNoOfSheets: "210",
    totalSqm: "714.720",
    availableSqm: "625.380",
    currency: "INR",
    amount: "286,900.00",
    remark: "Allocated for secondary furniture runs.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-PL-2026-0009",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-19"),
    invoiceNo: "PLY-2419",
    itemSrNo: "ITM-PLY-009",
    supplierName: "Panel Craft India",
    supplierItemName: "MR Grade Panel Refill",
    itemName: "MR Plywood",
    subCategory: "Utility",
    color: "Warm Beige",
    plywoodType: "MR",
    palletNo: "PLY-PAL-09",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "12 mm",
    totalNoOfSheets: "210",
    availableNoOfSheets: "188",
    totalSqm: "625.240",
    availableSqm: "559.760",
    currency: "INR",
    amount: "301,500.00",
    remark: "Replenishment for factory day shift.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-PL-2026-0010",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-21"),
    invoiceNo: "PLY-2421",
    itemSrNo: "ITM-PLY-010",
    supplierName: "Western Ply Boards",
    supplierItemName: "Fire Retardant Panel Stack",
    itemName: "Fire Retardant Plywood",
    subCategory: "Specialty",
    color: "Deep Brown",
    plywoodType: "FR",
    palletNo: "PLY-PAL-10",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "128",
    availableNoOfSheets: "119",
    totalSqm: "381.270",
    availableSqm: "354.470",
    currency: "INR",
    amount: "418,900.00",
    remark: "Reserved for hospitality interior fit-outs.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

export const plywoodDefinition: InventoryDefinition<StockRecord> = {
  slug: "plywood",
  title: "Plywood",
  listColumns: stockColumns,
  editFields: createInventoryEditFields(stockColumns, plywoodRows),
  formFields: createInventoryFormFields(plywoodRows),
  viewFields: createInventoryViewFields(stockColumns),
  rows: [],
  initialSort: { key: "inwardDate", direction: "desc" },
};
