import type { EnterpriseTableColumn } from "../../../components/data-display/EnterpriseDataTable";
import {
  asInventoryDate,
  createInventoryEditFields,
  createInventoryFormFields,
} from "../shared/inventoryDefinitionFields";
import {
  createInventoryRows,
  createInventoryViewFields,
} from "../shared/inventoryUtils";
import type { InventoryDefinition } from "../shared/types";
import {
  stockColumns,
  type StockRecord,
} from "../shared/stockInventoryColumns";


const mdfRows = createInventoryRows<StockRecord>("mdf", [
  {
    inwardSrNo: "INW-MDF-2026-0001",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-03"),
    invoiceNo: "MDF-2401",
    itemSrNo: "ITM-MDF-001",
    supplierName: "Urban Board Industries",
    supplierItemName: "Standard MDF Board Pack",
    itemName: "Standard MDF",
    subCategory: "Interior",
    color: "Natural Brown",
    plywoodType: "Plain",
    palletNo: "MDF-PAL-01",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "200",
    availableNoOfSheets: "172",
    totalSqm: "595.360",
    availableSqm: "511.990",
    currency: "INR",
    amount: "248,600.00",
    remark: "Daily inward for panel processing.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0002",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-05"),
    invoiceNo: "MDF-2405",
    itemSrNo: "ITM-MDF-002",
    supplierName: "Boardline Panels",
    supplierItemName: "Prelam MDF Bundle",
    itemName: "Prelam MDF",
    subCategory: "Decorative",
    color: "Maple Beige",
    plywoodType: "Prelam",
    palletNo: "MDF-PAL-02",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "17 mm",
    totalNoOfSheets: "168",
    availableNoOfSheets: "151",
    totalSqm: "500.100",
    availableSqm: "449.480",
    currency: "INR",
    amount: "292,400.00",
    remark: "Used for wardrobe shutter programs.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "19",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0003",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-07"),
    invoiceNo: "MDF-2407",
    itemSrNo: "ITM-MDF-003",
    supplierName: "Decorcore Sheets",
    supplierItemName: "High Density MDF Stack",
    itemName: "High Density MDF",
    subCategory: "Structural",
    color: "Smoke Brown",
    plywoodType: "HDF",
    palletNo: "MDF-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "156",
    availableNoOfSheets: "138",
    totalSqm: "464.380",
    availableSqm: "410.790",
    currency: "INR",
    amount: "318,900.00",
    remark: "Factory-preferred for CNC routing.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0004",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-09"),
    invoiceNo: "MDF-7719",
    itemSrNo: "ITM-MDF-004",
    supplierName: "Scandic Wood Surfaces",
    supplierItemName: "Moisture Resistant MDF Set",
    itemName: "MR MDF",
    subCategory: "Specialty",
    color: "Warm Grey",
    plywoodType: "MR",
    palletNo: "MDF-PAL-04",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "120",
    availableNoOfSheets: "102",
    totalSqm: "375.000",
    availableSqm: "318.750",
    currency: "EUR",
    amount: "5,620.00",
    remark: "Reserved for washroom vanity programs.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0005",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-11"),
    invoiceNo: "MDF-2411",
    itemSrNo: "ITM-MDF-005",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Flexi MDF Rollout Bundle",
    itemName: "Flexible MDF",
    subCategory: "Specialty",
    color: "Coffee Brown",
    plywoodType: "Flexible",
    palletNo: "MDF-PAL-05",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "6 mm",
    totalNoOfSheets: "240",
    availableNoOfSheets: "210",
    totalSqm: "714.720",
    availableSqm: "625.380",
    currency: "INR",
    amount: "274,900.00",
    remark: "Used for curved decorative panels.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0006",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-13"),
    invoiceNo: "MDF-2413",
    itemSrNo: "ITM-MDF-006",
    supplierName: "Royal Laminates India",
    supplierItemName: "Exterior Grade MDF Pack",
    itemName: "Exterior MDF",
    subCategory: "Exterior",
    color: "Deep Walnut",
    plywoodType: "Exterior",
    palletNo: "MDF-PAL-06",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "132",
    availableNoOfSheets: "118",
    totalSqm: "392.910",
    availableSqm: "351.240",
    currency: "INR",
    amount: "332,600.00",
    remark: "Allocated for facade backing panels.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0007",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-15"),
    invoiceNo: "MDF-7726",
    itemSrNo: "ITM-MDF-007",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Tone Veneered MDF Bundle",
    itemName: "Veneered MDF",
    subCategory: "Architectural",
    color: "Natural Oak",
    plywoodType: "Veneered",
    palletNo: "MDF-PAL-07",
    length: "2500 mm",
    width: "1250 mm",
    thickness: "18 mm",
    totalNoOfSheets: "118",
    availableNoOfSheets: "99",
    totalSqm: "368.750",
    availableSqm: "309.790",
    currency: "USD",
    amount: "5,980.00",
    remark: "Held for premium lobby wall cladding.",
    exchangeRate: "84.50",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0008",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-17"),
    invoiceNo: "MDF-2417",
    itemSrNo: "ITM-MDF-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Economy MDF Stock Lot",
    itemName: "Economy MDF",
    subCategory: "Utility",
    color: "Neutral Grey",
    plywoodType: "Plain",
    palletNo: "MDF-PAL-08",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "9 mm",
    totalNoOfSheets: "280",
    availableNoOfSheets: "248",
    totalSqm: "833.740",
    availableSqm: "738.750",
    currency: "INR",
    amount: "256,900.00",
    remark: "Allocated for secondary carcass work.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-MDF-2026-0009",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-19"),
    invoiceNo: "MDF-2419",
    itemSrNo: "ITM-MDF-009",
    supplierName: "Urban Board Industries",
    supplierItemName: "Fire Retardant MDF Panel Pack",
    itemName: "FR MDF",
    subCategory: "Specialty",
    color: "Muted Brown",
    plywoodType: "FR",
    palletNo: "MDF-PAL-09",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "154",
    availableNoOfSheets: "143",
    totalSqm: "458.340",
    availableSqm: "425.600",
    currency: "INR",
    amount: "344,800.00",
    remark: "Reserved for hospitality corridor package.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-MDF-2026-0010",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-21"),
    invoiceNo: "MDF-2421",
    itemSrNo: "ITM-MDF-010",
    supplierName: "Boardline Panels",
    supplierItemName: "Moisture Shield MDF Stack",
    itemName: "Moisture Shield MDF",
    subCategory: "Interior",
    color: "Satin Beige",
    plywoodType: "MR",
    palletNo: "MDF-PAL-10",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "146",
    availableNoOfSheets: "128",
    totalSqm: "434.890",
    availableSqm: "381.830",
    currency: "INR",
    amount: "318,400.00",
    remark: "To be issued against kitchen shutter schedule.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

export const mdfDefinition: InventoryDefinition<StockRecord> = {
  slug: "mdf",
  title: "MDF",
  listColumns: stockColumns,
  editFields: createInventoryEditFields(stockColumns, mdfRows),
  formFields: createInventoryFormFields(mdfRows),
  viewFields: createInventoryViewFields(stockColumns),
  rows: [],
  initialSort: { key: "inwardDate", direction: "desc" },
};
