import type { EnterpriseTableColumn } from "../../../components/data-display/EnterpriseDataTable";
import {
  asInventoryDate,
  createInventoryEditFields,
  createInventoryFormFields,
} from "../shared/inventoryDefinitionFields";
import {
  createInventoryRows,
  createInventoryViewFields,
} from "../shared/inventoryUtils";
import type { InventoryDefinition } from "../shared/types";
import {
  stockColumns,
  type StockRecord,
} from "../shared/stockInventoryColumns";


const veneerBlocksStockColumns: ReadonlyArray<EnterpriseTableColumn<StockRecord>> =
  stockColumns.map((column) =>
    column.key === "thickness" ? { ...column, label: "Height" } : column,
  );

const veneerBlocksRows = createInventoryRows<StockRecord>("veneer-blocks", [
  {
    inwardSrNo: "INW-VB-2026-0001",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-02"),
    invoiceNo: "VB-2401",
    itemSrNo: "ITM-VB-001",
    supplierName: "Arihant Veneers LLP",
    supplierItemName: "Oak Core Block Pack",
    itemName: "Oak Veneer Block",
    subCategory: "Quarter Cut",
    color: "Natural Oak",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-01",
    length: "2550 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "120",
    availableNoOfSheets: "92",
    totalSqm: "310.500",
    availableSqm: "237.820",
    currency: "INR",
    amount: "284,500.00",
    remark: "Issued partially to pressing.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0002",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-04"),
    invoiceNo: "VB-7712",
    itemSrNo: "ITM-VB-002",
    supplierName: "Euro Timber Exports",
    supplierItemName: "Walnut Architectural Block",
    itemName: "Walnut Veneer Block",
    subCategory: "Crown Cut",
    color: "Dark Walnut",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-02",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "19 mm",
    totalNoOfSheets: "96",
    availableNoOfSheets: "81",
    totalSqm: "324.000",
    availableSqm: "273.370",
    currency: "USD",
    amount: "5,920.00",
    remark: "Reserved for premium furniture line.",
    exchangeRate: "84.25",
    shift: "Morning",
    workers: "22",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0003",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-06"),
    invoiceNo: "VB-1189",
    itemSrNo: "ITM-VB-003",
    supplierName: "Shree Wood Panels",
    supplierItemName: "Teak Natural Stock Block",
    itemName: "Teak Veneer Block",
    subCategory: "Natural",
    color: "Golden Teak",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-03",
    length: "2440 mm",
    width: "1220 mm",
    thickness: "16 mm",
    totalNoOfSheets: "140",
    availableNoOfSheets: "140",
    totalSqm: "417.000",
    availableSqm: "417.000",
    currency: "INR",
    amount: "318,600.00",
    remark: "Fresh inward pending line allocation.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "16",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0004",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-08"),
    invoiceNo: "VB-2407",
    itemSrNo: "ITM-VB-004",
    supplierName: "Prime Timber Sources",
    supplierItemName: "Ash Core Assembly Block",
    itemName: "Ash Veneer Block",
    subCategory: "Crown Cut",
    color: "Soft Ash",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-04",
    length: "2500 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "110",
    availableNoOfSheets: "78",
    totalSqm: "335.500",
    availableSqm: "237.900",
    currency: "INR",
    amount: "276,400.00",
    remark: "Shortfall due to issued samples.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "19",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0005",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-10"),
    invoiceNo: "VB-7720",
    itemSrNo: "ITM-VB-005",
    supplierName: "Nordic Veneer House",
    supplierItemName: "Oak Rift Cut Structural Block",
    itemName: "Oak Veneer Block",
    subCategory: "Rift Cut",
    color: "Smoked Natural",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-05",
    length: "2800 mm",
    width: "1250 mm",
    thickness: "20 mm",
    totalNoOfSheets: "88",
    availableNoOfSheets: "63",
    totalSqm: "308.000",
    availableSqm: "220.500",
    currency: "EUR",
    amount: "6,250.00",
    remark: "Held for export-panel planning.",
    exchangeRate: "91.10",
    shift: "Morning",
    workers: "20",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0006",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-12"),
    invoiceNo: "VB-1198",
    itemSrNo: "ITM-VB-006",
    supplierName: "Mewar Decorative Woods",
    supplierItemName: "Walnut Standard Block Pack",
    itemName: "Walnut Veneer Block",
    subCategory: "Quarter Cut",
    color: "Rich Walnut",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-06",
    length: "2480 mm",
    width: "1220 mm",
    thickness: "18 mm",
    totalNoOfSheets: "102",
    availableNoOfSheets: "84",
    totalSqm: "303.400",
    availableSqm: "249.270",
    currency: "INR",
    amount: "295,900.00",
    remark: "Supplier label matched inward purchase order.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "17",
    noOfWorkingHours: "7.5",
    noOfTotalHours: "8.5",
  },
  {
    inwardSrNo: "INW-VB-2026-0007",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-14"),
    invoiceNo: "VB-2415",
    itemSrNo: "ITM-VB-007",
    supplierName: "Heritage Panel Works",
    supplierItemName: "Teak Interior Block Bundle",
    itemName: "Teak Veneer Block",
    subCategory: "Crown Cut",
    color: "Honey Teak",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-07",
    length: "2450 mm",
    width: "1210 mm",
    thickness: "17 mm",
    totalNoOfSheets: "126",
    availableNoOfSheets: "101",
    totalSqm: "372.600",
    availableSqm: "298.700",
    currency: "INR",
    amount: "264,750.00",
    remark: "Allocated partially to factory cutting line.",
    exchangeRate: "1.00",
    shift: "General",
    workers: "21",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0008",
    inwardType: "Domestic",
    inwardDate: asInventoryDate("2026-06-16"),
    invoiceNo: "VB-1210",
    itemSrNo: "ITM-VB-008",
    supplierName: "City Timber Traders",
    supplierItemName: "Ash Light Production Block",
    itemName: "Ash Veneer Block",
    subCategory: "Natural",
    color: "Soft Grey",
    plywoodType: "Commercial",
    palletNo: "VB-PAL-08",
    length: "2350 mm",
    width: "1180 mm",
    thickness: "16 mm",
    totalNoOfSheets: "132",
    availableNoOfSheets: "132",
    totalSqm: "367.200",
    availableSqm: "367.200",
    currency: "INR",
    amount: "236,300.00",
    remark: "Awaiting QC tagging for warehouse transfer.",
    exchangeRate: "1.00",
    shift: "Morning",
    workers: "15",
    noOfWorkingHours: "7.0",
    noOfTotalHours: "8.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0009",
    inwardType: "Import",
    inwardDate: asInventoryDate("2026-06-18"),
    invoiceNo: "VB-7744",
    itemSrNo: "ITM-VB-009",
    supplierName: "Baltic Timber Supply",
    supplierItemName: "Oak Premium Block Set",
    itemName: "Oak Veneer Block",
    subCategory: "Crown Cut",
    color: "Warm Natural",
    plywoodType: "Architectural",
    palletNo: "VB-PAL-09",
    length: "2700 mm",
    width: "1250 mm",
    thickness: "19 mm",
    totalNoOfSheets: "94",
    availableNoOfSheets: "68",
    totalSqm: "317.300",
    availableSqm: "229.480",
    currency: "USD",
    amount: "5,480.00",
    remark: "QC requested closer veneer serial verification.",
    exchangeRate: "84.40",
    shift: "General",
    workers: "23",
    noOfWorkingHours: "8.5",
    noOfTotalHours: "10.0",
  },
  {
    inwardSrNo: "INW-VB-2026-0010",
    inwardType: "Purchase",
    inwardDate: asInventoryDate("2026-06-20"),
    invoiceNo: "VB-2421",
    itemSrNo: "ITM-VB-010",
    supplierName: "Royal Laminates India",
    supplierItemName: "Walnut Feature Block Bundle",
    itemName: "Walnut Veneer Block",
    subCategory: "Natural",
    color: "Classic Walnut",
    plywoodType: "Decorative",
    palletNo: "VB-PAL-10",
    length: "2480 mm",
    width: "1230 mm",
    thickness: "18 mm",
    totalNoOfSheets: "108",
    availableNoOfSheets: "86",
    totalSqm: "314.800",
    availableSqm: "250.760",
    currency: "INR",
    amount: "301,200.00",
    remark: "Released for premium line issue.",
    exchangeRate: "1.00",
    shift: "Evening",
    workers: "18",
    noOfWorkingHours: "8.0",
    noOfTotalHours: "9.0",
  },
]);

export const veneerBlocksDefinition: InventoryDefinition<StockRecord> = {
  slug: "veneer-blocks",
  title: "Veneer Blocks",
  listColumns: veneerBlocksStockColumns,
  editFields: createInventoryEditFields(veneerBlocksStockColumns, veneerBlocksRows),
  formFields: createInventoryFormFields(veneerBlocksRows),
  viewFields: createInventoryViewFields(veneerBlocksStockColumns),
  rows: [],
  initialSort: { key: "inwardDate", direction: "desc" },
};
